export  default  {cn:{
    "ApplicationData": [
        {
            "No": "1",
            "Img": null,
            Width:'420.12',
            Height:'331.12',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
           "Imgxian":"app/images/xinz.png" ,
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Varuna</span> 帆船模型",
            "Year": "1907",
            "Area": "1900-1910年代",
            "Desc": "原是桌面装饰，连接了电线，用于召唤男管家<br/>黄<span class='fm-bl'>k</span>金，银，碧玉，木，珐琅",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Varuna",
            "Location": "SG",
            "Location2": "TD1",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"20世纪初，纽约富豪名流尤金·希金斯先生在上流社会有着极高的声望。他同时也是一位老练的帆船驾驶员，拥有众多豪华的游艇。其中，Varuna帆船深受希金斯先生的喜爱。丹麦国王、俄罗斯公爵及德意志皇帝等尊贵皇室皆是这架游艇的座上宾。1907年，希金斯先生为了纪念这艘心爱的游艇，亲自委托梵克雅宝制造了这件以Varuna帆船为模型的案头艺术品，作为一件通电的管家铃使用。Varuna帆船模型可谓是本次展览中最令人惊叹的珍宝之一。",
            "Zcontent":"首先，我们来到的是1910年代展厅。这个世纪之交，正是各种新旧思想和艺术形式交汇的时期。新艺术也正是在这个时期开始发展起来，对建筑、家具、珠宝设计、时尚等都产生了重要的影响。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        },
        {
            "No": "2",
            "Img": null,
            Width:'86.24',
            Height:'309.24',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Châtelaine</span> 驳领挂表",
            "Year": "1918",
            "Area": "1900-1910年代",
            "Desc": "铂金，缟玛瑙，钻石，罗缎",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Lapel Watch",
            "Location": "SG",
            "Location2": "WD1",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "ListHeight":"4.54rem",
            "Detail_content":"1920年代前后正处于装饰艺术风格发展的早期。<br />梵克雅宝从这种风格中汲取灵感，打造了许多于精致小巧而造型前卫的挂表。在腕表出现之前，上流社会的女性被这些挂表深深吸引，热衷于将它们佩戴在肩头或夹克的翻领之上，从而轻松读取时间。这枚以黑白为主色的挂表创作于1918年，是装饰艺术风格的典型之作。丝质缎带连接着由钻石及缟玛瑙镶嵌而成的图案及针扣，使其能够佩戴在衣服之上。",
            "Zcontent":"首先，我们来到的是1910年代展厅。这个世纪之交，正是各种新旧思想和艺术形式交汇的时期。新艺术也正是在这个时期开始发展起来，对建筑、家具、珠宝设计、时尚等都产生了重要的影响。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "3",
            "Img": null,
            'detailimgsize':"true",
            Width:'268.8',
            Height:'135.8',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "手镯",
            "Year": "1924",
            "Area": "1920年代",
            "Desc": "铂金，蓝宝石，红宝石，祖母绿，钻石， 缟玛瑙",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Bracelet Egyptian",
            "Location": "SG",
            "Location2": "SD1",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "ListHeight":"1.33rem",
            "Detail_content":"1922年，人类挖掘出了古埃及法老图坦卡蒙的墓穴，由此唤起了当时社会对埃及文化的浓厚兴趣，珠宝设计也从中汲取灵感。1922年到1925年间，<br />梵克雅宝创作了许多以埃及文化为创作灵感的手镯和胸针。正如这件诞生于1924年，由多彩宝石镶嵌而成的手镯。作品上呈现的是古埃及的祭祀画面，以及圣甲虫、狮身人面像、莲花、蜜蜂等象形图案。这件作品由凸圆形切割祖母绿、蓝宝石、红宝石、钻石及缟玛瑙镶嵌而成。以埃及文化为创作灵感的作品非常罕见，是令鉴赏家和收藏家趋之若鹜的珍宝。",
            "Zcontent":"咆哮的二十年代正值无忧无虑的战后间期，当时的巴黎是当之无愧的全球艺术中心。“新艺术”运动逐渐催生了风格简约的“装饰艺术”的诞生。符合全新美学特色的几何形状与自然主题继续在梵克雅宝的历史上扮演重要角色。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "4",
            "Img": null,
            Width:'398.52',
            Height:'376.52',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "百宝匣与山茶花胸针",
            "Year": "1938",
            "Area": "1930年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，玳瑁壳，镜子，隐密式镶嵌红宝石<br />可拆卸式胸针",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Minaudière avec clip Camélia",
            "Location": "SG",
            "Location2": "TD3",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"自1933年以来，百宝匣便是梵克雅宝的独家设计和代表作品。它精致小巧，却能收纳多种展现女性魅力精髓的物品，兼具优雅的外形和巧妙的功能性。这件制于1938年由黄<span class='fm-bl'>k</span>金打造的隐密式镶嵌百宝匣，饰有一枚可作为胸针单独佩戴的山茶花搭扣。轻启搭扣，映入眼帘的是一只粉盒、一对隐密式镶嵌的红宝石化妆盒、一支顶端带时钟的口红、邀舞卡、打火机和梳子。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "5",
            "Img": null,
            Width:'202.72',
            Height:'381.72',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Cadenas</span> 腕表",
            "Year": "1937",
            "Area": "1930年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Montre Cadenas",
            "Location": "SG",
            "Location2": "WD8",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"梵克雅宝自1920年代起就开始创作奢华的珠宝腕表。直至1935年，经由温莎公爵夫人的建议与启发，兼具精致外观和实用功能的Cadenas腕表终于诞生，倾斜的表盘令佩戴者能够于优雅低头时，隐秘地读取时间。这枚1937年制的Cadenas女士腕表饰以爪镶的红宝石，抽象主义风格的矩形表盘与一对黄金表链和谐辉映。Cadenas腕表不仅体现了1930年代风尚，时至今日依旧散发着经久不衰的魅力，成为梵克雅宝腕表系列的永恒经典。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "6",
            "Img": null,
            Width:'385.56',
            Height:'503.56',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Hawaï Passe Partout</span> 万用项链",
            "Year": "1939",
            "Area": "1930年代",
            "Desc": "可转换为一条手链或腰带，搭配可拆卸式胸针<br/>黄<span class='fm-bl'>k</span>金，红宝石，蓝宝石，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Bijou Passe Partout Hawaï",
            "Location": "SG",
            "Location2": "WD10",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"19世纪30-40年代，梵克雅宝的设计风格随着时代的发展而发生变化。万用珠宝的创新工艺有一物多用的效果，立即受到女性消费者的喜爱。万用珠宝是梵克雅宝领先完成的可转换式珠宝作品之一，于1938年获得专利。穿戴者可以根据心情的变化，不同场合与服饰，来进行各种搭配。在这条万用项链中，隐藏在两枚花卉下的金属轨道令黄 K 金蛇链能够自由滑动，从而变换为各种款式的项链、手链或腰带，而花朵也能作为胸针甚至夹式耳环单独配戴。这件作品多变的佩戴方式满足了日夜不同场合的多种装扮需求。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "7",
            "Img": null,
            Width:'269.55',
            Height:'262.55',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "蕾丝蝴蝶结胸针",
            "Year": "1949",
            "Area": "1940年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，铂金，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Noeud dentelle",
            "Location": "MG",
            "Location2": "CD1",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"文艺复兴时期到19世纪的绘画作品中所描绘的法国皇室，经常佩戴一些以织品装饰为灵感的珠宝。<br />梵克雅宝自创立至今，便深受这些独具法式优雅的配饰所影响，从而创作出以时装为灵感的一系列高级珠宝。其中，花边结饰本是时装界的一个基本装饰元素。在梵克雅宝的技艺之下，它融合蕾丝的纤巧细腻，巧妙地化身为蝴蝶结胸针，成为了一项经典设计。无论简约还是精致，这些花边结饰都以轻盈而优雅的姿态演绎着女性的温婉魅力。",
            "Zcontent":"1940年代处于二战期间，梵克雅宝工坊的运营步伐大幅减缓。贵宝石无法再运往欧洲，黄金作品被视作安全投资，因此梵克雅宝也重新回归黄<span class='fm-bl'>k</span>金珠宝的设计和制作中。尽管如此，这个年代仍然诞生了许多生动的彩色图案设计。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "8",
            "Img": null,
            Width:'231.15',
            Height:'388.15',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "美之精灵胸针",
            "Year": "约1944",
            "Area": "1940年代",
            "Desc": "原为芭芭拉·赫顿收藏<br />铂金，钻石，红宝石，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Spirit of Beauty",
            "Location": "MG",
            "Location2": "WD13",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"这枚仙子主题的胸针被有着“亿万宝贝”之誉的芭芭拉·赫顿所珍藏，她是梵克雅宝的忠实客户。梵克雅宝于1940年代创作的仙子主题胸针，富有感性诗意和优雅趣味，象征着女性特有的魅力。当天真而高贵的仙子悦动着活泼俏皮的身影，穿梭在梵克雅宝充满想象力的魔法森林中时，世家捕捉这些曼妙身姿与美好瞬间，化作款款瑰丽灵动的胸针。这枚镶有钻石、红宝石和祖母绿的美之精灵胸针便是其中的珍贵佳作之一。",
            "Zcontent":"1940年代处于二战期间，梵克雅宝工坊的运营步伐大幅减缓。贵宝石无法再运往欧洲，黄金作品被视作安全投资，因此梵克雅宝也重新回归黄<span class='fm-bl'>k</span>金珠宝的设计和制作中。尽管如此，这个年代仍然诞生了许多生动的彩色图案设计。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "9",
            "Img": null,
            Width:'267.95',
            Height:'334.95',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "西班牙舞伶胸针",
            "Year": "1941",
            "Area": "1940年代",
            "Desc": "铂金，黄<span class='fm-bl'>k</span>金，红宝石，祖母绿，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Danseuse espagnole",
            "Location": "MG",
            "Location2": "WD13",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1940年代，梵克雅宝创作的芭蕾舞伶胸针首度亮相于美国。当时正值二战时期，舞者精致优雅的造型给人们带来心灵的抚慰，被视作快乐和美好时光的象征。芭蕾舞伶胸针大获成功，而梵克雅宝与芭蕾的渊源也才刚刚拉开序幕。作为其中最动人的作品之一，这枚1941年制的西班牙舞伶胸针以轻灵的线条演绎着曼妙的舞姿。舞者的脸庞由梨形钻石雕刻而成，发梢、手中的扇子和荷叶边礼服均以铂金镶嵌着红宝石和祖母绿。",
            "Zcontent":"1940年代处于二战期间，梵克雅宝工坊的运营步伐大幅减缓。贵宝石无法再运往欧洲，黄金作品被视作安全投资，因此梵克雅宝也重新回归黄<span class='fm-bl'>k</span>金珠宝的设计和制作中。尽管如此，这个年代仍然诞生了许多生动的彩色图案设计。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "10",
            "Img": null,
            Width:'237.35',
            Height:'219.35',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "流苏耳环",
            "Year": "1953",
            "Area": "1950年代",
            "Desc": "原为伊朗王妃苏瑞亚收藏<br/>黄<span class='fm-bl'>k</span>金，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Collier cordes",
            "Location": "MG",
            "Location2": "",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": false,
            "Question": null,
            "QuesType": "",
            "Detail_content":"这对造型别致的流苏耳环曾被伊朗沙赫国王的第二任妻子苏瑞亚公主所珍藏。20世纪50年代中期到60年代末，梵克雅宝从别具一格的流苏造型中汲取灵感并运用于珠宝设计。流苏由经过精心修饰的黄<span class='fm-bl'>k</span>金穗带构成，可巧妙地装饰于手镯、胸针、耳环、项链、隐秘主题腕表和时装物件等多种作品之中。这对1953年创作的流苏耳环便是其中最具代表性的作品之一，耳环由黄<span class='fm-bl'>k</span>金和明亮式切割钻石打造而成。",
            "Zcontent":"接下来您将进入1950年代展厅。1950年代是万物复兴的时期，各行各业均创意涌动；得益于技术的革新和新型材质的研发，许多大胆设计更加游刃有余，进而惠及更多受众。战后时期，<br />梵克雅宝的珠宝设计再度回归经典造型。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "11",
            "Img": null,
            Width:'219.65',
            Height:'292.65',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "罂粟花胸针",
            "Year": "1952",
            "Area": "1950年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，铂金，钻石，隐密式镶嵌红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Serti Mystérieux",
            "Location": "MG",
            "Location2": "CD2",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"隐密式镶嵌从1933年获得专利起就一直是梵克雅宝的代名词，它能让宝石被紧密地镶嵌到小于0.2毫米的金属轨道中，不露出任何镶爪。其中运用的专业技术，只有极少数世家工艺大师能够掌握。由于制作过程非常复杂，掌握此项技艺的“黄金之手”也十分稀少，因此隐密式镶嵌的珠宝极为珍贵。这枚罂粟花胸针就是此项工艺的标志性作品之一，花蕊镶嵌了圆形切割钻石，花瓣则运用隐密式镶嵌工艺打造而成。",
            "Zcontent":"接下来您将进入1950年代展厅。1950年代是万物复兴的时期，各行各业均创意涌动；得益于技术的革新和新型材质的研发，许多大胆设计更加游刃有余，进而惠及更多受众。战后时期，梵克雅宝<br />的珠宝设计再度回归经典造型。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "12",
            "Img": null,
            Width:'255.3',
            Height:'288.3',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "印度图案胸针",
            "Year": "1966",
            "Area": "1960年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，钻石，红宝石，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Indian  Motif",
            "Location": "MG",
            "Location2": "CD3",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1920年代初，印度文化被传播到欧洲后便风靡整个欧洲上流社会。梵克雅宝在此时期的创作也深受这些元素的影响，印度珠宝的形状、设计、主题在<br />梵克雅宝的艺术作品中都深有体现。数位热衷于法国文化的印度皇室也成了梵克雅宝的忠实顾客。到了六七十年代，创新与探索不断持续，印度风格的珍宝在外观和工艺上都达到了新的高峰。梵克雅宝以起源于克什米尔的佩斯里图案为灵感，于1966年创作了这枚胸针。枕型切割的红宝石如花朵般被镶嵌于作品中央，周围散落的红宝石在钻石的衬托下焕发璀璨光泽。",
            "Zcontent":"在快乐主义盛行的1960年代，装饰艺术欣欣向荣，通过不同的形式、颜色和材质诠释其独有风格，一切新事物都充满了无限可能。诞生于1968年的Alhambra四叶草系列是梵克雅宝最具代表性的设计之一，自此世家不断推陈出新，以更多款式丰富了这个经典系列。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "13",
            "Img": null,
            Width:'258.75',
            Height:'265.75',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "圣诞玫瑰胸针和耳环套件",
            "Year": "1970（胸针），1971（耳环）",
            "Area": "1970年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，珊瑚，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "ROSE DE NOEL / PARURE CORAL",
            "Location": "MG",
            "Location2": "TD5",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1970年代，珊瑚除了被用于打造晚宴配饰，也经常点缀在适合日常佩戴并嵌有珍贵宝石的珠宝中。<br />梵克雅宝从具有强大生命力、象征着幸福与温暖的圣诞玫瑰中汲取灵感，以珊瑚、黄<span class='fm-bl'>k</span>金和钻石打造了这组圣诞玫瑰胸针和耳环套件。每朵花由6片花瓣组成，中心的花蕊处镶有明亮式切割钻石。这组作品被纳入La Boutique系列，成为1970年代标志性的设计之一。如今，圣诞玫瑰系列作品已化身为<br />梵克雅宝的珠宝系列，以珍珠母贝、缟玛瑙和红玉髓等多样材质延续着永恒的优雅。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "14",
            "Img": null,
            Width:'322.92',
            Height:'466.92',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Alhambra</span> 项链",
            "Year": "1971",
            "Area": "1970年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，绿玛瑙",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Alhambra",
            "Location": "MG",
            "Location2": "TD5",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"Alhambra系列自1960年代诞生以来，一直深受摩纳哥王妃格蕾丝·凯莉等名流的喜爱。1960年代是自由奔放的嬉皮时代，珠宝设计师们极具创新地将各种宝石混搭在一起，创作了风靡一时的长项链。1968年，Alhambra第一款长项链应运而生，边缘的黄<span class='fm-bl'>k</span>金金珠勾勒出四叶幸运图案隽永优雅的外形。Alhambra的设计灵感来自于象征幸运的四叶草，四片叶子分别代表健康、尊重、爱和财富。随着时代的变迁，Alhambra系列依旧散发着无穷魅力，四叶幸运图案也演变出许多别样的款式，如镶嵌着虎眼石、青金石、绿松石、玳瑁等。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "15",
            "Img": null,
            Width:'221.25',
            Height:'279.25',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "小鸟胸针",
            "Year": "1965",
            "Area": "1960年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，铂金，钻石，蓝宝石，绿松石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Le bestiaire",
            "Location": "MG",
            "Location2": "WD19",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1954年，梵克雅宝推出了便于日常佩戴的La Boutique系列动物胸针。这些富有幻想的缤纷作品一经推出就在世界各地大受欢迎，就连格蕾丝·凯莉王妃和杰奎琳·肯尼迪·奥纳西斯等名流也深陷其迷人魅力。该系列的灵感源于漫画，包括眨眼的猫咪、手捧绿松石松果的松鼠等众多幽默诙谐的胸针造型。大象、老虎、狮子、鸭子、长颈鹿、乌龟、小鸟、贵宾犬等也各以奇趣的姿态丰富了La Boutique系列。作品以黄<span class='fm-bl'>k</span>金镶嵌精美宝石，如绿松石、缟玛瑙、青金石、紫水晶等。",
            "Zcontent":"在快乐主义盛行的1960年代，装饰艺术欣欣向荣，通过不同的形式、颜色和材质诠释其独有风格，一切新事物都充满了无限可能。诞生于1968年的Alhambra四叶草系列是梵克雅宝最具代表性的设计之一，自此世家不断推陈出新，以更多款式丰富了这个经典系列。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "16",
            "Img": null,
            Width:'356.28',
            Height:'363.28',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Panka</span> 项链和耳环套件",
            "Year": "1973（项链），1974（耳环）",
            "Area": "1970年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，钻石，绿松石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Parure Panka",
            "Location": "MG",
            "Location2": "CD4",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"自装饰艺术风格盛行的1920年代起，兼具艺术气息和缤纷色彩，以及奢华的巴洛克设计的印度风格元素，成为了梵克雅宝成就经典之作的灵感源泉。吸引梵克雅宝踏上探索东方和“一千零一夜”世界的旅程。雅宝家族的两兄弟克劳德和皮埃尔经常为了寻找珍贵的宝石而远赴印度。这件珠宝套装由黄<span class='fm-bl'>k</span>金镶嵌的圆形和椭圆型凸面绿松石以及圆形钻石制成，宝石与项链的造型相得益彰，充满迷人的异域风情。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "17",
            "Img": null,
            Width:'254.76',
            Height:'279.76',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Marqueterie</span> 风格胸针和耳环套件",
            "Year": "1985",
            "Area": "1980-1990年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，珊瑚，青金石，孔雀石，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Marqueterie",
            "Location": "MG",
            "Location2": "WD22",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1980年代，时尚风格重归简约质朴，珠宝套装设计更加典雅，通常以几何线条勾勒出别致的结构。<br />梵克雅宝以珊瑚、象牙、珍珠母贝等有机材质，搭配黄<span class='fm-bl'>k</span>金或彩色宝石，推出了许多色彩鲜艳又别具新意的作品。其中，这件由耳环和胸针组成的珠宝套装兼具装饰与收藏意义。缤纷的纹饰由珊瑚、孔雀石与青金石和谐交织而成，铺镶钻石则彰显了<br />梵克雅宝的匠心工艺。无论日常还是晚宴，这组造型别致、尺寸适中的作品都能装点佩戴者的优雅身姿。",
            "Zcontent":"接下来您将进入1980和1990年代展厅。1980年代，珠宝设计风格重返简约有序、庄重内敛。贵宝石珠宝在这一时期进一步风靡，成为备受追捧的日常佩戴珠宝。梵克雅宝的珠宝套装设计更加典雅，但始终别具新意，以几何线条巧妙勾勒出别致结构。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "18",
            "Img": null,
            Width:'384.36',
            Height:'414.36',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Sublime</span> 项链",
            "Year": "1988",
            "Area": "1980-1990年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，钻石，隐密式镶嵌红宝石和祖母绿",
            "Desc2": "私人藏品",
            "PieceName": "Collier Sublime",
            "Location": "MG",
            "Location2": "CD5",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"上世纪70年代，珠宝艺术界兴起了一股以珍贵宝石搭配装饰性宝石的风潮，呈现的作品色彩鲜艳且设计巧妙。带有吊坠或者长穗的长项链就是当时极具象征意义的作品之一。随后的10年里，因潮流趋势回归简约质朴，长项链逐渐退出设计舞台，取而代之的是衣领式短项链或项圈，经常搭配戒指或手镯组成珠宝套装。这条创作于1988年的Sublime项链便是短项链的代表作之一。它以黄金镶嵌着钻石，装饰部分的红宝石花朵和祖母绿树叶则由独特的隐密式镶嵌工艺打造而成。",
            "Zcontent":"接下来您将进入1980和1990年代展厅。1980年代，珠宝设计风格重返简约有序、庄重内敛。贵宝石珠宝在这一时期进一步风靡，成为备受追捧的日常佩戴珠宝。梵克雅宝的珠宝套装设计更加典雅，但始终别具新意，以几何线条巧妙勾勒出别致结构。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "19",
            "Img": null,
            Width:'376.92',
            Height:'427.92',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "威尼斯项链",
            "Year": "1985",
            "Area": "1980-1990年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，钻石",
            "Desc2": "Richters of Palm Beach 藏品",
            "PieceName": "Venise",
            "Location": "MG",
            "Location2": "CD5",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"20世纪80至90年代间，潮流风格回归于简约质朴，与十年前的嬉皮风格形成了鲜明对比。梵克雅宝推出的珠宝套装以经典的造型，将其中的创新技术与精致结构娓娓道来。短项链以其简约的外观在此时的珠宝设计中脱颖而出。它们有的硬朗，有的柔软，有的装饰着一簇花朵。正如这件威尼斯项链，项链上的花朵由明亮式切割的钻石构成，或自由或交错地排列于黄金轨道之上。",
            "Zcontent":"接下来您将进入1980和1990年代展厅。1980年代，珠宝设计风格重返简约有序、庄重内敛。贵宝石珠宝在这一时期进一步风靡，成为备受追捧的日常佩戴珠宝。梵克雅宝的珠宝套装设计更加典雅，但始终别具新意，以几何线条巧妙勾勒出别致结构。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "20",
            "Img": null,
            Width:'321.44',
            Height:'269.44',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "蝴蝶胸针",
            "Year": "2012",
            "Area": "2000-2010年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，漆绘，珍珠母贝，木，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clips Papillons",
            "Location": "MG",
            "Location2": "WD27",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"20世纪初兴起的“新艺术运动”中，蝴蝶图案经常被运用于珠宝设计。自1920年代起，梵克雅宝就被蝶翼的优雅与轻盈深深吸引，设计了大量蝴蝶造型的珠宝。2008年，梵克雅宝联手日本漆器创作大师箱濑淳一，创作了限量的蝴绘蝴蝶系列。不对称的翅膀上巧妙地饰以菊花、蕨类、樱花、竹子和松木等传统日本图案。质地轻薄的透明宝石，诠释了蝴蝶灵动的美感。这枚创作于2012年的蝴蝶胸针便是这个系列的代表作之一。",
            "Zcontent":"2002年起，梵克雅宝开始推出年度主题高级珠宝系列。大自然与各种传说成为了世家珍爱的灵感源泉，珠宝此时变得更具叙事意味。大胆前卫的造型，搭配缤纷多彩的宝石，彻底革新了高级珠宝的设计与制作传统，开辟出该领域的新疆界。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "21",
            "Img": null,
            Width:'291.64',
            Height:'246.64',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "三角形图案耳环和手镯套件",
            "Year": "1997",
            "Area": "1980-1990年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，蛇纹木",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Fleur bois",
            "Location": "MG",
            "Location2": "WD25",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"这组珠宝套件由木材镶嵌着三角形图案的黄k金打造而成。20世纪初，人们认为接触木制的物件就可以得到好运。梵克雅宝自1916年起就将木材用于珠宝作品，如硬质的发夹、手镯、手镯上的装饰，或一些饰有珍贵宝石的戒指。木材的美好寓意为<br />梵克雅宝带来了巨大的成功。在1930年代的时计作品中也出现了木材的身影。木质表盘搭配皮革或罗缎表带组成腕表，或直接装饰于怀表和翻领手表上。到了70年代，更多珠宝作品运用了木材这一元素，在随后的20年里一直大受欢迎。梵克雅宝在20世纪90年代末打造的这套木质的珠宝套件，由蛇纹木镶嵌着黄<span class='fm-bl'>k</span>金的三角形图案，手镯上可以刻上姓名或喜欢的句子，在当时非常受欢迎。",
            "Zcontent":"接下来您将进入1980和1990年代展厅。1980年代，珠宝设计风格重返简约有序、庄重内敛。贵宝石珠宝在这一时期进一步风靡，成为备受追捧的日常佩戴珠宝。梵克雅宝的珠宝套装设计更加典雅，但始终别具新意，以几何线条巧妙勾勒出别致结构。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "22",
            "Img": null,
            Width:'374.76',
            Height:'536.76',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "维多利亚项链和耳环套件",
            "Year": "2008",
            "Area": "2000-2010年代",
            "Desc": "白K金，钻石，蓝宝石，养殖珍珠",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Parure Victoria",
            "Location": "MG",
            "Location2": "CD7",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"自2002年起，梵克雅宝就以诗意自然、神话传说和传奇舞会为灵感源泉，每年推出年度主题高级珠宝系列，珠宝在此时变得更具故事性。在这些臻品佳作之中，花园系列的作品种类繁多，饰有最为珍贵的宝石。这些宝石精妙绝伦，高度还原了大自然的缤纷色彩。从古典的法式到浪漫的英式，从文艺复兴时代的意式到禅意的日式，梵克雅宝演绎了不同风格的花园。这组维多利亚项链和耳环套件便是英式花园的浪漫化身。凸圆形切割的粉色蓝宝石在交相辉映中散发着微妙而和谐的光芒。",
            "Zcontent":"2002年起，梵克雅宝开始推出年度主题高级珠宝系列。大自然与各种传说成为了世家珍爱的灵感源泉，珠宝此时变得更具叙事意味。大胆前卫的造型，搭配缤纷多彩的宝石，彻底革新了高级珠宝的设计与制作传统，开辟出该领域的新疆界。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "23",
            "Img": null,
            Width:'346.24',
            Height:'329.24',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "飞鸟项链和耳环套件",
            "Year": "2011",
            "Area": "2000-2010年代",
            "Desc": "“Bals de Légende”系列<br />黄<span class='fm-bl'>k</span>金，彩色蓝宝石，钻石",
            "Desc2": "私人藏品",
            "PieceName": "Collier et motifs d’oreilles Oiseau",
            "Location": "MG",
            "Location2": "WD29",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"飞鸟是梵克雅宝和法国小说家普鲁斯特都极为珍视的灵感源泉。普鲁斯特经常将笔下的女主人公比作鸟儿。无论是鸵鸟、蜂鸟还是极乐鸟，它们柔软轻盈的羽毛是“美好时代”的象征之一。当羽毛出现在普鲁斯特笔下的优雅女士身边时，便展现了从未有过的时髦感。梵克雅宝描绘的飞鸟通常表现为展翅翱翔或振翅欲飞，都是处于动态或即将进入动态。正如这件飞鸟作品，梵克雅宝的珠宝工艺大师秉承严苛的工艺要求，将羽毛一片片组装起来，呈现了鸟儿振翅欲飞的灵动美态。",
            "Zcontent":"2002年起，梵克雅宝开始推出年度主题高级珠宝系列。大自然与各种传说成为了世家珍爱的灵感源泉，珠宝此时变得更具叙事意味。大胆前卫的造型，搭配缤纷多彩的宝石，彻底革新了高级珠宝的设计与制作传统，开辟出该领域的新疆界。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "25",
            "Img": null,
            "nomore": '1',
            Width:'315.84',
            Height:'266.84',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "化妆盒",
            "Year": "1926",
            "Area": "1920年代",
            "Desc": "红宝石，祖母绿，黄色蓝宝石，钻石，翡翠，珐琅",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Roses vanity case （AKA Nécessaire）",
            "Location": "LG",
            "Location2": "D1",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Touchable interaction",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": false,
            "HasWord": false,
            "HasImg": true,
            "Question": null,
            "QuesType": "PicGame",
            "AudioUrl":"app/media/cn/2VCA_Mand_Necessaire.mp3",
            "VideoUrl":"app/video/2.mp4",
            "Detail_content":"1920年代，装饰艺术于欧洲盛行，并经1925年的巴黎现代工业和装饰艺术博览会后风靡全球。这一时期，梵克雅宝的设计受装饰艺术风格的影响，于1926年创作了这件玫瑰图案的化妆盒。在这个年代，为了时刻保持迷人风姿，时尚优雅的女性们都会随身携带精致的化妆盒，用来放置镜子，粉盒，口红，药盒，手绢和邀舞卡等随身物品。您现在所见的这枚化妆盒，底座使用的材质是黄<span class='fm-bl'>k</span>金和铂金，上面镶嵌着淡紫色翡翠；化妆盒表面所饰的玫瑰花，由玫瑰切割钻石、祖母绿、红宝石和水滴形黄色蓝宝石铺镶而成；边缘细节处的黑色和绿色珐琅也令化妆盒的整体造型更为精致。",
            "Zcontent":"咆哮的二十年代正值无忧无虑的战后间期，当时的巴黎是当之无愧的全球艺术中心。“新艺术”运动逐渐催生了风格简约的“装饰艺术”的诞生。符合全新美学特色的几何形状与自然主题继续在梵克雅宝的历史上扮演重要角色。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "24",
            "Img": null,
            "nomore": '1',
            Width:'483.84',
            Height:'423.84',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "项圈",
            "Year": "1929",
            "Area": "1920年代",
            "Desc": "原为埃及法伊莎公主收藏<br />铂金，祖母绿，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Collerette",
            "Location": "LG",
            "Location2": "D2",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": false,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "曾收藏这条项圈的<span>法伊莎</span>公主来自于哪个国家？ ",
                "Answer": [
                    {
                        "game_name":"印度",
                        "game_src":"app/images/6cn.png"
                    },
                    {
                        "game_name":"埃及",
                        "game_src":"app/images/5cn.png"
                    },
                    {
                        "game_name":"希腊",
                        "game_src":"app/images/8cn.png"
                    },
                    {
                        "game_name":"伊朗",
                        "game_src":"app/images/7cn.png"
                    }
                ],
                "Rightanswer":2
            },
            "QuesType": "SelectCard",
            "AudioUrl":"app/media/cn/1VCA_Mand_Collaret.mp3",
            "VideoUrl":"/app/video/1.mp4",
            "Detail_content":"梵克雅宝于1929年打造了这件装饰艺术风格的祖母绿项圈，并在1937年对其加以改造。同年，埃及皇家驻法国代表替埃及法伊莎公主购置了这条项圈。这位风姿绰约的埃及公主对珠宝十分热衷，并且品味非凡，梵克雅宝的作品总能得到她的喜爱。<br/>您眼前的这件曾为埃及法伊莎公主所拥有的项圈，其采用的祖母绿来自最佳产地哥伦比亚。项圈的底座部分，由矩形切割和肩章形切割的钻石铺镶而成。吊坠则由10颗品质非凡、总重达165克拉的水滴形祖母绿构成。其中，9颗祖母绿在前面悬垂一圈，体积从上而下逐渐递增，镶嵌在一排长方形和矩形切割钻石交替的底座上；另一颗祖母绿则镶嵌在后颈搭扣处，尽显佩戴者的雍容华美。除此之外，法伊莎公主还曾拥有梵克雅宝另一件运用隐密式镶嵌工艺的牡丹胸针，该件作品也在此次展览中展出，大家不妨寻觅一下这件作品的踪迹。",
            "Zcontent":"从多元繁荣的1920年代，到工艺日臻完善的21世纪，每一件标志性经典作品的诞生，都铭刻着梵克雅宝对时代之美的感悟。这些臻品佳作随着历史的演进而熠熠闪光，将传承百年的风华与永恒的优雅艺术娓娓道来。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
       
        {
            "No": "26",
            "Img": null,
            'detailimgsize':"true",
            Width:'303.96',
            Height:'243.96',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "菊花胸针",
            "Year": "1937",
            "Area": "1930年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，铂金，钻石，隐密式镶嵌红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Chrysanthème",
            "Location": "LG",
            "Location2": "D3",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"诗人陶渊明曾写道：“采菊东篱下，悠然见南山”。菊花是秋天的象征，以无限的生命力盛开在寒风中，因此自古以来就被赋予美好的意象。18世纪后，菊花由中国传到欧洲，时装设计师对这些源自东方的艺术形态进行了再度演绎，将其应用于创作之中。这枚胸针的灵感也由此而来。经验丰富的珠宝工艺大师运用隐密式镶嵌法，以总重达140克拉的835颗红宝石打造了卷曲的花瓣，展现了菊花的美好形态。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "27",
            "Img": null,
            "nomore": '1',
            Width:'307.84',
            Height:'332.84',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "牡丹胸针",
            "Year": "1937",
            "Area": "1930年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，铂金，钻石，隐密式镶嵌红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Peony",
            "Location": "LG",
            "Location2": "D4",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这枚胸针采用了什么镶嵌技术？",
                "Answer": [
                    "爪镶",
                    "隐密式镶嵌",
                    "包镶",
                    "雪花镶嵌"
                ],
                "Rightanswer":2
            },
            "QuesType": "NormalChoice",
            "AudioUrl":"app/media/cn/3VCA_Mand_PeonyClip.mp3",
            "VideoUrl":"app/video/3.mp4",
            "Detail_content":"自然是梵克雅宝一直以来最为珍视的灵感之一。这枚以牡丹花为主题的胸针，是梵克雅宝在1937年受埃及法伊莎公主的委托而打造，采用了梵克雅宝于1933年获得专利权的隐密式镶嵌工艺。这件兼具了自然花卉主题和精湛工艺的作品，可以说是<br />梵克雅宝在1930年代最具代表性的艺术杰作之一。<br/> 这枚胸针最初的设计方案是一对牡丹花造型的双花胸针，其中一朵合拢，一朵绽放。佩戴方式可以双花合璧，也可以一枝独秀。胸针的花瓣镶嵌有646颗缅甸红宝石，与196颗重达30克拉的圆形及长方形切割的钻石打造的叶片交相辉映，花芯则由6颗重达100克拉的椭圆型刻面红宝石组成。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "32",
            "Img": null,
            "nomore": '1',
            Width:'358.56',
            Height:'389.56',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "项圈",
            "Year": "1939",
            "Area": "1930年代",
            "Desc": "原为埃及王后纳丝莉收藏<br/>铂金，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Collerette",
            "Location": "LG",
            "Location2": "D5",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": false,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这条项圈创作于哪一年?",
                "Answer": [
                    "1921",
                    "1933",
                    "1936",
                    "1939"
                ],
                "Rightanswer":"1939"
            },
            "QuesType": "YearInput",
            "AudioUrl":"app/media/cn/8VCA_Mand_Collaret2.mp3",
            "VideoUrl":"app/video/8.mp4",
            "Detail_content":"这件创作于1939年的项圈，原为埃及纳丝莉王后所有。作为一位热爱法式风格的珠宝爱好者，<br />她向梵克雅宝定制过许多豪华珠宝作品。这条项圈便是其中的一件杰作，她曾佩戴着这条项圈，出席了女儿法丝娅公主和伊朗王储穆罕默德·礼萨·巴列维的婚礼，纳丝莉王后曾写信给梵克雅宝，表示她“对珠宝的制作十分满意。”这条让纳丝莉王后十分喜爱的项圈由铂金和钻石打造而成，637颗重达204.03克拉的柱状切割钻石镶嵌在三条垂链上，在项链中心组成一个“太阳”造型，其上又悬挂四条垂链。这条项圈具有装饰艺术风格，完美对称，其中正中心这颗钻石重达6克拉。",
            "Zcontent":"1929年，华尔街股市崩盘，但这并未影响到1930年代盛行的创新风潮。在这个时期，梵克雅宝众多的创新设计也奠定了其卓尔不群的声誉和独具匠心的风格：百宝匣取代了晚宴包，隐密式镶嵌令珠宝的金属底座隐形，更显璀璨光华。            ",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "29",
            "nomore": '1',
            "Img": null,
            Width:'253.45',
            Height:'349.45',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "珠片设计胸针",
            "Year": "1948",
            "Area": "1940年代",
            "Desc": "铂金，黄<span class='fm-bl'>k</span>金，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Paillettes",
            "Location": "LG",
            "Location2": "D7",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这枚胸针中运用的<span>Paillette</span>珠片元素灵感来源于？",
                "Answer": [
                    "高级定制服装",
                    "诗意自然",
                    "神话故事",
                    "传奇舞会"
                ],
                "Rightanswer":[1,2]
            },
            "QuesType": "NormalChoice",
            "AudioUrl":"app/media/cn/5VCA_Mand_SequinsClip.mp3",
            "VideoUrl":"app/video/5.mp4",
            "Detail_content":"1930年代开始，梵克雅宝从高定时装中获取灵感，推出了 “Paillette”高定珠片设计元素。这一时期，梵克雅宝创作的一系列作品都巧妙地运用了这一珠片设计元素。1936年，梵克雅宝首次将它运用到一条项链上。在1942年的一则广告中，它亮相于流苏造型胸针的两个吊坠上，化身为一款带有结节的缀饰。到了1950年代，梵克雅宝为伊朗公主苏瑞亚特别定制的珠宝套装中也有它的身影。<br/>这枚创作于1948年的珠片设计胸针，便是运用“Paillette”高定珠片设计元素的代表作。作品以钻石点缀在抛光的金珠饰片中央，打造出耀目的花束造型。熠熠闪耀的亮片描绘着流丽而灵动的线条，将造型衬托得更为精致优雅。",
            "Zcontent":"1940年代处于二战期间，梵克雅宝工坊的运营步伐大幅减缓。贵宝石无法再运往欧洲，黄金作品被视作安全投资，因此梵克雅宝也重新回归黄<span class='fm-bl'>k</span>金珠宝的设计和制作中。尽管如此，这个年代仍然诞生了许多生动的彩色图案设计。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "28",
            "Img": null,
            "nomore": '1',
            Width:'251.85',
            Height:'335.85',
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "珠片设计芭蕾舞伶胸针",
            "Year": "1953",
            "Area": "1950年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，钻石，红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Danseuse paillettes",
            "Location": "LG",
            "Location2": "",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这枚胸针演绎的少女正在跳哪种舞蹈？",
                "Answer": [
                    {
                        "game_name":"芭蕾",
                        "game_src":"app/images/13.png"
                    },
                    {
                        "game_name":"华尔兹",
                        "game_src":"app/images/14.png"
                    },
                    {
                        "game_name":"现代舞",
                        "game_src":"app/images/15.png"
                    },
                    {
                        "game_name":"弗拉明戈",
                        "game_src":"app/images/16.png"
                    }
                ],
                "Rightanswer":1
            },
            "QuesType": "SelectCard",
            "AudioUrl":"app/media/cn/4VCA_Mand_SequinedDancerClip.mp3",
            "VideoUrl":"app/video/4.mp4",
            "Detail_content":"芭蕾舞伶代表着女性的优雅形象，是梵克雅宝钟爱的设计主题之一。自从1940年第一批芭蕾舞伶胸针在纽约问世以来，翩然起舞的芭蕾舞伶就降临到<br />梵克雅宝的世界。时至今日，依旧是梵克雅宝作品中优雅柔美的经典标志。这枚创作于1953年的珠片设计芭蕾舞伶胸针，运用了“Paillettes”珠片，这来源于高级定制时装的设计元素。胸针以红宝石及黄<span class='fm-bl'>k</span>金饰片装点舞者华美裙摆。裙摆上饰有以镂空工艺打造的花边，随着舞者的姿态而展现灵动的美感，细述着一段芭蕾与珠宝的浪漫之缘。",
            "Zcontent":"接下来您将进入1950年代展厅。1950年代是万物复兴的时期，各行各业均创意涌动；得益于技术的革新和新型材质的研发，许多大胆设计更加游刃有余，进而惠及更多受众。战后时期，梵克雅宝的珠宝设计再度回归经典造型。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "30",
            "nomore": '1',
            "Img": null,
            Width:'411.96',
            Height:'578.48',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "<span class='fm-bl'>Zip </span><span>项链</span>",
            "Year": "1951",
            "Area": "1950年代",
            "Desc": "可转换为一条手链<br/>黄<span class='fm-bl'>k</span>金，铂金，钻石，红宝石，蓝宝石，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Zip",
            "Location": "LG",
            "Location2": "D8",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "<span>Zip</span><span>项链的创作灵感来源于哪位名人的创意</span>?",
                "Answer": [
                  "伊丽莎白·泰勒",
                  "温莎公爵夫人",
                  "埃及艳后",
                  "芭芭拉·赫顿",
                ],
                "Rightanswer":2
            },
            "QuesType": "NormalChoice",
            "AudioUrl":"app/media/cn/6VCA_Mand_ZipNecklace.mp3",
            "VideoUrl":"app/video/6.mp4",
            "Detail_content":"Zip 项链以拉链为创作灵感，是梵克雅宝最为独特的经典设计之一。拉链最早出现在飞行员夹克和航海员制服上。到了1930年代，女性逐渐抛开传统束缚，拥抱独立自由，拉链这一元素才被时装界广泛采用。据传1938年左右，来自独立自由的美国、富有前卫思想的温莎公爵夫人，建议梵克雅宝当时的艺术总监芮妮·皮森特以拉链为原型创作一款珠宝。直到1950年，拉链造型的珠宝终于问世。<br/>您看到的这件创作于1951年的ZIP项链便是其中的代表作之一。项链由黄<span class='fm-bl'>k</span>金人字形链节构成，佩戴者可以拉动拉链，使其打开成为一条别致的项链，或者轻拉中央的流苏，使其完全闭合成一条手链。",
            "Zcontent":"接下来您将进入1950年代展厅。1950年代是万物复兴的时期，各行各业均创意涌动；得益于技术的革新和新型材质的研发，许多大胆设计更加游刃有余，进而惠及更多受众。战后时期，梵克雅宝的珠宝设计再度回归经典造型。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "31",
            "Img": null,
            "nomore": '1',
            Width:'409.32',
            Height:'379.32',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "<span>Mystère IV</span> （神秘四号） 项链",
            "Year": "1956",
            "Area": "1950年代",
            "Desc": "马塞尔·达索赠予杰奎琳·奥里奥尔<br/>铂金，黄<span class='fm-bl'>k</span>金，钻石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Mystère IV",
            "Location": "LG",
            "Location2": "D9",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这条项链以飞机作为设计灵感的原因是？",
                "Answer": [
                    "纪念雅宝兄弟的旅程",
                    "致敬第一位驾驶飞机速度<br/>超过音障的女飞行员",
                    "庆祝第一架超音速客机的诞生",
                    "源于一部以飞机为主题的电影"
                ],
                "Rightanswer":2
            },
            "QuesType": "NormalChoice",
            "AudioUrl":"app/media/cn/7VCA_Mand_MystereIV.mp3",
            "VideoUrl":"app/video/7.mp4",
            "Detail_content":"1956年，梵克雅宝受法国著名航空工业家马塞尔·达索委托，为杰奎琳·奥里奥尔定制一款项链。杰奎琳·奥里奥尔是法国第一位女性试飞员，也是第一位驾驶飞机实现超音速飞行的女飞行员。在20世纪50-60年代之间，她曾5次打破女子100英里近程飞行纪录。为了纪念这位女飞行员的杰出成就与优雅魅力，这款唤起着许多年轻女性对飞行和冒险热情的项链应运而生。项链从针织编织中汲取灵感，以黄<span class='fm-bl'>k</span>金制成轻灵的纱网，象征着神秘四号飞机的传奇航程。飞机滑翔过天际留下的痕迹，化作了一串晶莹钻石，镶嵌于细腻平滑的线条上。",
            "Zcontent":"接下来您将进入1950年代展厅。1950年代是万物复兴的时期，各行各业均创意涌动；得益于技术的革新和新型材质的研发，许多大胆设计更加游刃有余，进而惠及更多受众。战后时期，梵克雅宝的珠宝设计再度回归经典造型。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "39",
            "Img": null,
            "imgsizes":"true",
            'detailimgsizemore':"true",
            Width:'361.8',
            Height:'271.8',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Lion Barquerolles</span> 项带",
            "Year": "1971",
            "Area": "1970年代",
            "Desc": "原为伊丽莎白·泰勒收藏<br/>项链可转换为两条手链和一枚胸针<br/>黄<span class='fm-bl'>k</span>金，钻石，祖母绿",
            "Desc2": "私人藏品",
            "PieceName": "Bijouterie chaines",
            "Location": "LG",
            "Location2": "",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"这条创作于1971年的项带是美国影星伊丽莎白·泰勒珍藏之作。这位美丽的女士同时也是一位非常著名的私人珠宝收藏家。她对珠宝的热爱从小就已开始，曾提到：“母亲说我出生后八天都未曾睁眼。而当我睁开眼看到的第一件东西就是她的订婚戒指。我被深深地吸引了！”在她众多的传奇珠宝收藏中，就有这条理查德·伯顿为庆祝她成为祖母而倾情相赠的项带。这条由梵克雅宝以钻石和黄<span class='fm-bl'>k</span>金打造的项带，可转化为两个手镯、一枚饰有祖母绿眼睛的狮子胸针和一个双环吊坠。伊丽莎白·泰勒在看到这件作品的第一时间就热切地表达了对此的喜爱。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "35",
            "Img": null,
            Width:'312.12',
            Height:'509.12',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "项链",
            "Year": "1971",
            "Area": "1970年代",
            "Desc": "原为阿迦汗王后收藏<br/>项链可调节长度，或转换成三条手链和一枚胸针<br/>黄<span class='fm-bl'>k</span>金，钻石，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Aga Khan",
            "Location": "LG",
            "Location2": "D11",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"这条创作于1971年的项链曾为伊朗王妃萨丽麦殿下所收藏。萨丽麦王妃是一位身份尊贵的名媛，对艺术和珠宝怀有诚挚的热情和过人的鉴赏天赋。她的一生中，收集了许多精妙绝伦的珠宝作品，每一件均由独一无二的珍贵宝石制成。在这些非凡珠宝中，这套由梵克雅宝打造的印度风情项链格外引人瞩目。项链由总重达52克拉的745颗钻石和478克拉的44颗18世纪祖母绿组成，可转化为两条手链和一条吊坠项链。它是梵克雅宝多元化可转换式珠宝设计的经典范例，仅以一个搭扣就巧妙演绎了珠宝的转换。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "36",
            "Img": null,
            "nomore": '1',
            Width:'274.85',
            Height:'339.85',
            "list_recommend":"推荐展品",
            "Imgxia":"app/images/xia.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgxian":"app/images/xinz.png",
            "Title": "五叶胸针",
            "Year": "1967",
            "Area": "1960年代",
            "Desc": "原为希腊传奇女高音歌唱家玛丽亚·卡拉斯收藏<br/>铂金，钻石，红宝石",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Cinq Feuilles",
            "Location": "LG",
            "Location2": "D12",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": false,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "曾收藏这枚胸针的<span>玛丽亚·卡拉斯</span>所从事的职业是?",
                "Answer": [
                    {
                        "game_name":"芭蕾舞者",
                        "game_src":"app/images/1.png"
                    },
                    {
                        "game_name":"女高音歌唱家",
                        "game_src":"app/images/2.png"
                    },
                    {
                        "game_name":"油画画家",
                        "game_src":"app/images/3.png"
                    },
                    {
                        "game_name":"钢琴家",
                        "game_src":"app/images/4.png"
                    }
                ],
                "Rightanswer":2
            },
            "QuesType": "SelectCard",
            "AudioUrl":"app/media/cn/9VCA_Mand_FiveLeavesClip.mp3",
            "VideoUrl":"app/video/9.mp4",
            "Detail_content":"这枚制作于 1967 年的胸针原为歌剧女王玛丽亚·卡拉斯所有，如今已成为梵克雅宝典藏臻品。玛丽亚·卡拉斯是一位具有传奇色彩的希腊女高音歌唱家。同时，她对珠宝艺术也充满了热情，是一位颇具鉴赏力的珠宝收藏家。每当她身着一袭长裙，佩戴着梵克雅宝的精美珠宝出现时，都能引起一阵轰动。在众多由梵克雅宝为她特别打造的作品中，就有这枚她曾多次佩戴着亮相于各大重要场合的五叶胸针。胸针镶有重达15.77克拉的缅甸椭圆形红宝石，以及总重达16.35克拉的圆形、榄尖形和长方形切割的钻石。",
            "Zcontent":"在快乐主义盛行的1960年代，装饰艺术欣欣向荣，通过不同的形式、颜色和材质诠释其独有风格，一切新事物都充满了无限可能。诞生于1968年的Alhambra四叶草系列是梵克雅宝最具代表性的设计之一，自此世家不断推陈出新，以更多款式丰富了这个经典系列。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "34",
            "Img": null,
            Width:'282.24',
            Height:'234.24',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "<span>Walska</span> 黄钻吊坠飞鸟胸针",
            "Year": "1971-1972",
            "Area": "1970年代",
            "Desc": "吊坠原为二十世纪三四十年代<br />著名歌唱家伽娜·瓦斯卡（1887-1984）收藏<br />胸针可转换为一枚饰有水滴形黄钻的吊坠、鸟尾组成的胸针和一对由翅膀组成的耳环 <br />黄<span class='fm-bl'>k</span>金，黄钻，钻石，蓝宝石，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Walska",
            "Location": "LG",
            "Location2": "D10",
            "Contenthqwillprovide": "TEXT",
            "ExtraRequestByChinaTeam": "",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"1930年，这颗重达96.62克拉的黄色梨形钻石由波兰著名歌剧演唱家伽娜·瓦斯卡所珍藏，她将此饰于一条独特的吊坠上。当这颗钻石在1971年的苏富比拍卖会上易主之后，新的所有者便委托梵克雅宝将这颗精美绝伦的黄钻镶嵌在由黄 K 金、祖母绿和蓝宝石制成的鸟儿之上，以庆祝她于 1972 年喜得贵子。这件黄钻吊坠飞鸟胸针运用了梵克雅宝传承已久的可转换式设计：黄色梨形钻石正缀于鸟喙之上，可取下以吊坠的造型单独佩戴；鸟儿的双翼可拆卸，作为耳环佩戴；鸟的身体可拆卸，作为胸针佩戴。",
            "Zcontent":"1970年代是战后光辉三十年的末期，此时发明创造层出不穷，人们的生活方式日新月异，新型材质不断涌现。大胆前卫的时尚风格也影响了珠宝的设计。高级珠宝依然受到梵克雅宝贵宾的青睐，但贵金属珠宝逐渐打破传统，自成一格。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        
        
        {
            "No": "37",
            "Img": null,
            "nomore": '1',
            Width:'347.04',
            Height:'270.14',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxia":"app/images/xia.png",
            "Imgxian":"app/images/xinz.png",
            "Imgjianmi":"app/images/detail/cnjiemi.png",
            "Imgjianmi2":"app/images/detail/enjiemi.png",
            "Imgyaoshi":"app/images/icon/yaoshi.png",
            "Title": "龙形胸针",
            "Year": "1969",
            "Area": "1960年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，珊瑚，祖母绿",
            "Desc2": "梵克雅宝典藏",
            "PieceName": "Clip Dragon",
            "Location": "LG",
            "Location2": "D14",
            "Contenthqwillprovide": "TEXT + VIDEO+AUDIO",
            "ExtraRequestByChinaTeam": "Interaction:Quiz",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": true,
            "HasVideo": true,
            "HasWord": false,
            "HasImg": true,
            "Question": {
                "Ques": "这枚胸针的眼睛由什么宝石制成?",
                "Answer": [
                    {
                        "game_name":"祖母绿",
                        "game_src":"app/images/9cn.png"
                    },
                    {
                        "game_name":"石榴石",
                        "game_src":"app/images/10cn.png"
                    },
                    {
                        "game_name":"橄榄石",
                        "game_src":"app/images/11cn.png"
                    },
                    {
                        "game_name":"绿松石",
                        "game_src":"app/images/12cn.png"
                    }
                    
                ],
                "Rightanswer":1
            },
            "QuesType": "SelectCard",
            "AudioUrl":"app/media/cn/10VCA_Mand_GragonClip.mp3",
            "VideoUrl":"app/video/10.mp4",
            "Detail_content":"异域文明一直是梵克雅宝珍视的灵感源泉之一。在远东文明的神话传说中，龙是最为古老的神话动物。在中国，龙的起源可以追溯到公元前3000年，代表着幸福，永生，繁荣和活力。同时，龙也被视作中国古代皇帝的帝王象征，具有驱除邪灵的力量。正因如此，在艺术作品中，龙的形象也经常被运用于图案设计。1965年至1970年末期，梵克雅宝深受异域文明的吸引，创作出的珠宝作品极具异国风情。正如这枚诞生于1969年的龙形胸针，完美地演绎了中国龙的形象：由黄金打造的覆满鳞片的狭长龙身曲卷缠绕着、搭配镶嵌祖母绿的双眼，四肢抱着一颗红珊瑚雕刻的圆球，再现了神话中“祥龙戏珠”玄幻景象，寓意着为新年带来好运。",
            "Zcontent":"在快乐主义盛行的1960年代，装饰艺术欣欣向荣，通过不同的形式、颜色和材质诠释其独有风格，一切新事物都充满了无限可能。诞生于1968年的Alhambra四叶草系列是梵克雅宝最具代表性的设计之一，自此世家不断推陈出新，以更多款式丰富了这个经典系列。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "38",  
            "Img": null,
            "imgsizes":"true",
            'detailimgsizemore':"true",
            Width:'280.48',
            Height:'279.48',
            "medium12":"mediumtransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "锦鲤手镯腕表",
            "Year": "2014",
            "Area": "2000-2010年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，锰铝榴石，黄色蓝宝石，帕拉伊巴碧玺，黑色尖晶石，钻石",
            "Desc2": "私人藏品",
            "PieceName": "Carpe Koï watch bracelet",
            "Location": "LG",
            "Location2": "",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": false,
            "Question": {
                "Ques": "多字",
                "Answer": []
            },
            "QuesType": "",
            "Detail_content":"在梵克雅宝以自然为灵感而创作的众多珠宝中，这件致敬日本文化的锦鲤手镯腕表尤为珍贵。锦鲤以明亮的色彩点缀着禅式庭院的静谧景致，犹如爱的化身于宁静中带来一丝盎然生气。腕表共镶嵌了8000颗彩色宝石，经3450个小时的精细手工打造才得以呈现。鱼身饰以黄色蓝宝石及金黄色的锰铝石榴石，营造了层层递进的渐变色彩。鱼尾边的几缕涟漪则由蓝色的帕拉伊巴碧玺构成，彰显了水底世界的宁静深邃。这款高级珠宝时计臻品仿如护身符般环绕玉手，只需轻按鱼尾即可将锁扣松开，显露出隐藏在鱼嘴里的表盘。",
            "Zcontent":"2002年起，梵克雅宝开始推出年度主题高级珠宝系列。大自然与各种传说成为了世家珍爱的灵感源泉，珠宝此时变得更具叙事意味。大胆前卫的造型，搭配缤纷多彩的宝石，彻底革新了高级珠宝的设计与制作传统，开辟出该领域的新疆界。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        },
        {
            "No": "33",
            "Img": null,
            Width:'521.64',
            Height:'440.64',
            'large8':"laegetransform",
            "list_recommend":"推荐展品",
            "Imgxian":"app/images/xinz.png",
            "Imgxia":"app/images/xia.png",
            "Title": "凌波仙子自动人偶装置",
            "Year": "2016",
            "Area": "2000-2010年代",
            "Desc": "黄<span class='fm-bl'>k</span>金，银，钻石，海蓝宝石，蛋白石，黑檀木，珐琅，彩色蓝宝石，隐密式镶嵌红宝石",
            "Desc2": "私人藏品",
            "PieceName": "A fairylike scene",
            "Location": "LG",
            "Location2": "",
            "Contenthqwillprovide": "TEXT+AUDIO",
            "ExtraRequestByChinaTeam": "需要录制音频",
            "HsChina": true,
            "HasEn": true,
            "HasAudio": false,
            "HasVideo": false,
            "HasWord": true,
            "HasImg": true,
            "Question": null,
            "QuesType": "",
            "Detail_content":"2017年日内瓦国际高级钟表展上，这款凌波仙子自动人偶装置首度亮相。凌波仙子自动人偶装置是梵克雅宝Extraordinary Object系列的首款作品，作品融汇梵克雅宝悠久的高级珠宝制作传统和高级制表工艺，谱写了诗意时间的全新篇章。凌波仙子自动人偶装置运用的制表工艺，包括逆跳时针和手动机械活动装置。启动作品的机械活动装置，长达50秒的精彩童话故事便翩然上演。细致地捕捉了大自然稍纵即逝的灵动美态：仙子从睡梦中苏醒时的优雅，以及珍贵宝石和珐琅的微妙色彩变化。在精确报时的同时，呈现了诗意梦幻的视觉盛宴。",
            "Zcontent":"2002年起，梵克雅宝开始推出年度主题高级珠宝系列。大自然与各种传说成为了世家珍爱的灵感源泉，珠宝此时变得更具叙事意味。大胆前卫的造型，搭配缤纷多彩的宝石，彻底革新了高级珠宝的设计与制作传统，开辟出该领域的新疆界。",
            "Econtent":"In spite of the Wall Street crash in 1929, this was a highly innovative decade. At Van Cleef & Arpels, a productive collaboration between the artistic director Renée Puissant and the designer René-Sim Lacaze got under way. These were the years during which new designs contributed to definitively establishing Van Cleef & Arpels’ reputation and style: the Minaudière, that replaced the evening bag, and the famous Mystery Setting, an incredible piece of technical prowess that rendered the mount invisible. The middle of the decade was marked by a preference for jewelry made of gold, like the Ludo bracelet."
        
        }
    ]
}}